#ifndef WIDGETID_H
#define WIDGETID_H

enum
{
	/* Menubar */
	ID_MENU_NEW_PRJ = 1002,
	ID_MENU_OPEN_PRJ,
	ID_MENU_SAVE_PRJ,
	ID_MENU_SAVE_AS_PRJ,

	/* Tree */
	ID_TREECTRL = 10003,
	ID_TREE_MENU_ITEM_ADDNODE_CHILD,
	ID_TREE_MENU_ITEM_ADDNODE_SIBLING,
	ID_TREE_MENU_ITEM_DELNODE,
	ID_TREE_MENU_ITEM_RENAME,

	/* Log */
	ID_TOGGLE_LOGWINDOW = 10001
};

#endif // WIDGETID_H